/**
 * StockAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface StockMovement { 
    id?: number;
    productId?: number;
    date?: string;
    quantity?: number;
    type?: string | null;
    product?: Product;
}

